### ISSUE TITLE
Require host when configuring nginx

### ISSUE THREAD

**Issue by appinteractive** [gimlet-io/gimlet-stack#14]
Should the host field be mendetory when configuring nginx?

**Reproduce:**
1. Add Prometheus und Loki with `stack configure`
2. Also add Nginx without a host
3. See broken host config in helm-releases/grafana.yaml

<img width="380" alt="grafik" src="https://user-images.githubusercontent.com/432828/120216554-76f9bc00-c237-11eb-91c7-fae2cc79da93.png">

**Comment by laszlocph** [comment]
You are right! 

Let me make it so. 🙌 for the report!

**Comment by laszlocph** [comment]
Note to self: if `enabled` then `host` is mandatory structures can be achieved by https://react-jsonschema-form.readthedocs.io/en/latest/usage/dependencies/

We probably need a non gui based validation too. Like `stack lint` or `stack verify` to validate schema correctness.

**Comment by laszlocph** [comment]
https://github.com/gimlet-io/gimlet-stack/pull/17

**Comment by laszlocph** [comment]
[v0.2.0](https://github.com/gimlet-io/gimlet-stack/releases/tag/v0.2.0) got this covered.

Make sure to update `stack` before run `stack configure` and `stack generate`
