### ISSUE TITLE
Use JIT Mode in Tailwind and fix missing prose class

### ISSUE THREAD

**Issue by appinteractive** [gimlet-io/gimlet-stack#15]
Currently the formatting of readme`s in the `stack configure` ui is broken. I think it is because of the `prose` class does not get generated or purged. Therefore I would use the JIT mode so it is visible in development what comes out at the end (in contrast to the purge mode)

See: https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode

`prose` has no effect as of now:
<img width="995" alt="grafik" src="https://user-images.githubusercontent.com/432828/120222643-8d584580-c240-11eb-8dfc-c051d9af79d3.png">

**Comment by laszlocph** [comment]
Are you using the latest release?

It supposed to have a fix for this: https://github.com/gimlet-io/gimlet-stack/releases/tag/v0.1.1

**Comment by appinteractive** [comment]
Uhhh 😬 seems you where faster on pushing then I on pulling 🙈 sorry for that. But still I think using JIT will be beneficial and Improve development and decrease build times.

**Comment by laszlocph** [comment]
oh, JIT is cool, wasn't aware of it. I will enable it when next touching the frontend.

Thanks for headsup!
